Controllers/CityController.cs
using Microsoft.AspNetCore.Mvc;
using paperProject.Models;
using paperProject.Services;
using System;
using System.Collections.Generic;
using System.Linq;

namespace paperProject.Controllers
{
    public class CityController : Controller
    {
        public IActionResult Index()
        {
            using (var db = new PaperProjectContext())
            {
               var cities=db.City.Take(100);
            }

            return View();
        }

        public IActionResult List(int page)
        {
            var cityList = new List<City>();
            using (var db = new PaperProjectContext())
            {
                cityList = db.City.Take(page).ToList();
            }

            return Json(cityList);
        }
    }
}

Controllers/FlightController.cs
using Microsoft.AspNetCore.Mvc;
using paperProject.Models;
using System.Diagnostics;
using paperProject.Services;
using System.Collections.Generic;
using System.Linq;
using paperProject.ViewModels;
using AutoMapper;
using System;

namespace paperProject.Controllers
{
    public class FlightController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Line()
        {
            return View();
        }
        public IActionResult LineData(int page)
        {
            var flightList = new List<Flight>();
            using (var db = new PaperProjectContext())
            {
                flightList = db.Flight.Take(page).ToList();
                
            }

            return Json(flightList);
        }
        public IActionResult Station()
        {
            return View();
        }

        public IActionResult StationData(int page)
        {
            var cityList = new List<CityView>();
            try
            {
                using (var db = new PaperProjectContext())
                {
                    var list = db.City.Take(100).ToList();
                    cityList=Mapper.Map<List<CityView>>(list);
                    cityList.ForEach(k =>
                    {
                        var flight=db.Flight.FirstOrDefault(p=>p.acn==k.CityName);
                        if(flight!=null)
                            k.StationName = flight.apbn;
                    });
                }
            }
            catch (Exception ex)
            {

            }

            return Json(cityList.Where(k=>!string.IsNullOrEmpty(k.StationName)).Take(10).ToList());
        }

        public IActionResult About()
        {
            ViewData["Message"] = "Your application description page.";

            return View();
        }

        public IActionResult Contact()
        {
            ViewData["Message"] = "Your contact page.";

            return View();
        }

        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Controllers/ShipController.cs
using Microsoft.AspNetCore.Mvc;
using paperProject.Models;
using System.Diagnostics;
using System.Collections.Generic;
using paperProject.Services;
using AutoMapper;
using paperProject.ViewModels;
using System;
using System.Linq;

namespace paperProject.Controllers
{
    public class ShipController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Line()
        {
            return View();
        }
        public IActionResult LineData(int page)
        {
            var shipList = new List<Ship>();
            using (var db = new PaperProjectContext())
            {
                shipList = db.Ship.Take(page).ToList();
            }

            return Json(shipList);
        }
        public IActionResult Station()
        {
            return View();
        }

        public IActionResult StationData(int page)
        {
            var cityList = new List<CityView>();
            try
            {
                using (var db = new PaperProjectContext())
                {
                    var list = db.Ship.ToList();
                    var cities = db.City.ToList();
                    cityList=Mapper.Map<List<CityView>>(cities);
                    list.ForEach(k =>
                    {
                        var city= cityList.FirstOrDefault(p=>p.CityName.Contains(k.from_city));
                        if(city != null)
                            city.StationName = k.from_dock_name;
                    });
                }
            }
            catch (Exception ex)
            {

            }

            return Json(cityList.Where(k=>!string.IsNullOrEmpty(k.StationName)).ToList());
        }
    }
}

Controllers/TrainController.cs
using Microsoft.AspNetCore.Mvc;
using paperProject.Models;
using paperProject.Services;
using System;
using System.Collections.Generic;
using System.Linq;
using paperProject.ViewModels;
using AutoMapper;

namespace paperProject.Controllers
{
    public class TrainController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Line()
        {
            return View();
        }
        public IActionResult LineData(int page)
        {
            var trainList = new List<TrainView>();
            try
            {
                using (var db = new PaperProjectContext())
                {
                    var list = db.Train.Take(page).ToList();
                    trainList=Mapper.Map<List<TrainView>>(list);
                    trainList.ForEach(k =>
                    {
                        k.TrainStations = db.TrainStation.Where(p => k.train_code == p.station_train_code).OrderBy(p => p.station_no).ToList();
                    });
                }
            }
            catch (Exception ex)
            {

            }

            return Json(trainList);
        }

        public IActionResult Station()
        {
            return View();
        }

        public IActionResult StationData(int page)
        {
            var cityList = new List<CityView>();
            try
            {
                using (var db = new PaperProjectContext())
                {
                    var list = db.City.Take(100).ToList();
                    cityList=Mapper.Map<List<CityView>>(list);
                    cityList.ForEach(k =>
                    {
                        var train=db.Train.Where(p=>p.from_station.Contains(k.CityName)).OrderBy(p=>p.from_station).ToList();
                        if(train!=null){
                            var stations="";
                            train.Select(p=>p.from_station).Distinct().ToList().ForEach(p=>{
                                stations+=p+"，";
                            });
                            
                            k.StationName = stations.TrimEnd(new char[]{'，'});
                        }
                    });
                }
            }
            catch (Exception ex)
            {

            }

            return Json(cityList.Where(k=>!string.IsNullOrEmpty(k.StationName)).Take(10).ToList());
        }

        public IActionResult About()
        {
            ViewData["Message"] = "Your application description page.";

            return View();
        }

        public IActionResult Contact()
        {
            ViewData["Message"] = "Your contact page.";

            return View();
        }
    }
}

Views/Shared/_Layout - 复制.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"]</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top navbar-color">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">paperProject</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Train" asp-action="Index">火车</a></li>
                    <li><a asp-area="" asp-controller="Flight" asp-action="Index">飞机</a></li>
                    <li><a asp-area="" asp-controller="Ship" asp-action="Index">轮船</a></li>
                </ul>
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2017 - paperProject</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>

Views/Shared/_Layout.cshtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta http-equiv="content-type" content="text/html; charset=utf-8" />
    <title>中长途旅客出行线路规划平台</title>
    <link rel="stylesheet" type="text/css" href="~/css/reset.css" media="screen" />
    <link rel="stylesheet" type="text/css" href="~/css/text.css" media="screen" />
    <link rel="stylesheet" type="text/css" href="~/css/grid.css" media="screen" />
    <link rel="stylesheet" type="text/css" href="~/css/layout.css" media="screen" />
    <link rel="stylesheet" type="text/css" href="~/css/nav.css" media="screen" />
    <!--[if IE 6]><link rel="stylesheet" type="text/css" href="~/css/ie6.css" media="screen" /><![endif]-->
    <!--[if IE 7]><link rel="stylesheet" type="text/css" href="~/css/ie.css" media="screen" /><![endif]-->
    <link href="~/css/fancy-button/fancy-button.css" rel="stylesheet" type="text/css" />
    <!--Jquery UI CSS-->
    <link href="~/css/themes/base/jquery.ui.all.css" rel="stylesheet" type="text/css" />
    <!-- BEGIN: load jquery -->
    <script src="~/js/jquery-1.6.4.min.js" type="text/javascript"></script>
    <script type="text/javascript" src="~/js/jquery-ui/jquery.ui.core.min.js"></script>
    <script src="~/js/jquery-ui/jquery.ui.widget.min.js" type="text/javascript"></script>
    <script src="~/js/jquery-ui/jquery.ui.accordion.min.js" type="text/javascript"></script>
    <script src="~/js/jquery-ui/jquery.effects.core.min.js" type="text/javascript"></script>
    <script src="~/js/jquery-ui/jquery.effects.slide.min.js" type="text/javascript"></script>
    <script src="~/js/jquery-ui/jquery.ui.mouse.min.js" type="text/javascript"></script>
    <script src="~/js/jquery-ui/jquery.ui.sortable.min.js" type="text/javascript"></script>
    <script src="~/js/table/jquery.dataTables.min.js" type="text/javascript"></script>
    <!-- END: load jquery -->
    <!--jQuery Date Picker-->
    <script src="~/js/jquery-ui/jquery.ui.widget.min.js" type="text/javascript"></script>
    <script src="~/js/jquery-ui/jquery.ui.datepicker.min.js" type="text/javascript"></script>
    <script src="~/js/jquery-ui/jquery.ui.progressbar.min.js" type="text/javascript"></script>
    <!-- jQuery dialog related-->
    <script src="~/js/jquery-ui/external/jquery.bgiframe-2.1.2.js" type="text/javascript"></script>
    <script src="~/js/jquery-ui/jquery.ui.mouse.min.js" type="text/javascript"></script>
    <script src="~/js/jquery-ui/jquery.ui.draggable.min.js" type="text/javascript"></script>
    <script src="~/js/jquery-ui/jquery.ui.position.min.js" type="text/javascript"></script>
    <script src="~/js/jquery-ui/jquery.ui.resizable.min.js" type="text/javascript"></script>
    <script src="~/js/jquery-ui/jquery.ui.dialog.min.js" type="text/javascript"></script>
    <script src="~/js/jquery-ui/jquery.effects.core.min.js" type="text/javascript"></script>
    <script src="~/js/jquery-ui/jquery.effects.blind.min.js" type="text/javascript"></script>
    <script src="~/js/jquery-ui/jquery.effects.explode.min.js" type="text/javascript"></script>
    <!-- jQuery dialog end here-->
    <script src="~/js/jquery-ui/jquery.ui.accordion.min.js" type="text/javascript"></script>
    <!--Fancy Button-->
    <script src="~/js/fancy-button/fancy-button.js" type="text/javascript"></script>
    <script src="~/js/setup.js" type="text/javascript"></script>
    <!-- Load TinyMCE -->
    <script src="~/js/tiny-mce/jquery.tinymce.js" type="text/javascript"></script>
    <!-- END: load jquery -->
    <script src="~/js/setup.js" type="text/javascript"></script>


    <script type="text/javascript">

        $(document).ready(function () {
            //setupLeftMenu();
            setupTinyMCE();
            setupProgressbar('progress-bar');
            setDatePicker('date-picker1');
            setDatePicker('date-picker2');
            setupDialogBox('dialog', 'opener');
            $('input[type="checkbox"]').fancybutton();
            $('input[type="radio"]').fancybutton();

            $('.datatable').dataTable();
            setSidebarHeight();
            $("#example_info").text("1 到 10 条");
            $("#example_filter label").html("<label>搜索: <input type='text'></label>");
            $("#example_length").html('<label>显示 <select size="1" name="example_length"><option value="10" selected="selected">10</option><option value="25">25</option><option value="50">50</option><option value="100">100</option></select> 条</label>');
            
        });
    </script>
    <style>
        body {
            font-size:15px;
        }
        .prev-next {
            position: absolute;
            bottom: 1px;
            right: 100px;
        }

            .prev-next a {
                font-weight: bolder;
                text-decoration: underline
            }
    </style>
</head>
<body>
    <div class="container_12">
        <div class="grid_12 header-repeat">
            <div id="branding">
                <div class="floatleft" style="color: white;font-size: 25px;">
                    中长途旅客出行线路规划平台
                    @*<img src="~/img/logo.png" alt="Logo" />*@
                </div>
                <div class="clear">
                </div>
            </div>
        </div>
        <div class="clear">
        </div>
        <div class="grid_12">
            <ul class="nav main">
                <li class="ic-dashboard"><a href="dashboard.html"><span>数据集展示</span></a></li>
                <li class="ic-form-style"><a href="/Line/Search?type=1"><span>线路查询</span></a></li>
                @*<li class="ic-grid-tables"><a href="/Line/Search?type=2"><span>算法比较</span></a></li>*@
            </ul>
        </div>
        <div class="clear">
        </div>
        <div class="grid_2">
            <div class="box sidemenu">
                <div class="block" id="section-menu">
                    <ul class="section menu">
                        <li>
                            <a asp-controller="City" asp-action="Index">城市数据集</a>
                        </li>
                        <li>
                            <a class="menuitem">站点数据集</a>
                            <ul class="submenu">
                                @*<li><a asp-controller="Train" asp-action="Station">火车站点数据</a></li>
                                <li><a asp-controller="Flight" asp-action="Station">飞机站点数据</a></li>
                                <li><a asp-controller="Ship" asp-action="Station">轮船站点数据</a></li>*@
                            </ul>
                        </li>
                        <li>
                            <a class="menuitem">线路数据集</a>
                            <ul class="submenu">
                                <li><a asp-controller="Train" asp-action="Line">火车线路数据</a></li>
                                <li><a asp-controller="Flight" asp-action="Line">飞机线路数据</a></li>
                                <li><a asp-controller="Ship" asp-action="Line">轮船线路数据</a></li>
                            </ul>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
        <div class="grid_10">
            <div class="box round first grid">
                <h2>
                    @ViewData["Title"]
                </h2>
                <div class="block">
                    @RenderBody()
                </div>
            </div>
        </div>
        <div class="clear">
        </div>
    </div>
    <div class="clear">
    </div>
    <div id="site_info">
        <!-- <p>
            Copyright <a href="#">BlueWhale Admin</a>. All Rights Reserved.More Templates <a href="http://www.cssmoban.com/" target="_blank" title="模板之家">模板之家</a> - Collect from <a href="http://www.cssmoban.com/" title="网页模板" target="_blank">网页模板</a>
        </p> -->
    </div>
    <div class="prev-next">
        <a>上一页</a>
        <a>下一页</a>
        <!-- <input type="button" value="上一页"/>
        <input type="button" value="下一页"/> -->
    </div>
</body>
</html>

Views/Shared/_Layout0.cshtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta http-equiv="content-type" content="text/html; charset=utf-8" />
    <title>中长途旅客出行线路规划平台</title>
    <link rel="stylesheet" type="text/css" href="~/css/reset.css" media="screen" />
    <link rel="stylesheet" type="text/css" href="~/css/text.css" media="screen" />
    <link rel="stylesheet" type="text/css" href="~/css/grid.css" media="screen" />
    <link rel="stylesheet" type="text/css" href="~/css/layout.css" media="screen" />
    <link rel="stylesheet" type="text/css" href="~/css/nav.css" media="screen" />
    <!--[if IE 6]><link rel="stylesheet" type="text/css" href="~/css/ie6.css" media="screen" /><![endif]-->
    <!--[if IE 7]><link rel="stylesheet" type="text/css" href="~/css/ie.css" media="screen" /><![endif]-->
    <link href="~/css/fancy-button/fancy-button.css" rel="stylesheet" type="text/css" />
    <!--Jquery UI CSS-->
    <link href="~/css/themes/base/jquery.ui.all.css" rel="stylesheet" type="text/css" />
    <!-- BEGIN: load jquery -->
    <script src="~/js/jquery-1.6.4.min.js" type="text/javascript"></script>
    <script type="text/javascript" src="~/js/jquery-ui/jquery.ui.core.min.js"></script>
    <script src="~/js/jquery-ui/jquery.ui.widget.min.js" type="text/javascript"></script>
    <script src="~/js/jquery-ui/jquery.ui.accordion.min.js" type="text/javascript"></script>
    <script src="~/js/jquery-ui/jquery.effects.core.min.js" type="text/javascript"></script>
    <script src="~/js/jquery-ui/jquery.effects.slide.min.js" type="text/javascript"></script>
    <script src="~/js/jquery-ui/jquery.ui.mouse.min.js" type="text/javascript"></script>
    <script src="~/js/jquery-ui/jquery.ui.sortable.min.js" type="text/javascript"></script>
    <script src="~/js/table/jquery.dataTables.min.js" type="text/javascript"></script>
    <!-- END: load jquery -->
    <!--jQuery Date Picker-->
    <script src="~/js/jquery-ui/jquery.ui.widget.min.js" type="text/javascript"></script>
    <script src="~/js/jquery-ui/jquery.ui.datepicker.min.js" type="text/javascript"></script>
    <script src="~/js/jquery-ui/jquery.ui.progressbar.min.js" type="text/javascript"></script>
    <!-- jQuery dialog related-->
    <script src="~/js/jquery-ui/external/jquery.bgiframe-2.1.2.js" type="text/javascript"></script>
    <script src="~/js/jquery-ui/jquery.ui.mouse.min.js" type="text/javascript"></script>
    <script src="~/js/jquery-ui/jquery.ui.draggable.min.js" type="text/javascript"></script>
    <script src="~/js/jquery-ui/jquery.ui.position.min.js" type="text/javascript"></script>
    <script src="~/js/jquery-ui/jquery.ui.resizable.min.js" type="text/javascript"></script>
    <script src="~/js/jquery-ui/jquery.ui.dialog.min.js" type="text/javascript"></script>
    <script src="~/js/jquery-ui/jquery.effects.core.min.js" type="text/javascript"></script>
    <script src="~/js/jquery-ui/jquery.effects.blind.min.js" type="text/javascript"></script>
    <script src="~/js/jquery-ui/jquery.effects.explode.min.js" type="text/javascript"></script>
    <!-- jQuery dialog end here-->
    <script src="~/js/jquery-ui/jquery.ui.accordion.min.js" type="text/javascript"></script>
    <!--Fancy Button-->
    <script src="~/js/fancy-button/fancy-button.js" type="text/javascript"></script>
    <script src="~/js/setup.js" type="text/javascript"></script>
    <!-- Load TinyMCE -->
    <script src="~/js/tiny-mce/jquery.tinymce.js" type="text/javascript"></script>
    <!-- END: load jquery -->
    <script src="~/js/setup.js" type="text/javascript"></script>


    <script type="text/javascript">

        $(document).ready(function () {
            //setupLeftMenu();
            setupTinyMCE();
            setupProgressbar('progress-bar');
            setDatePicker('date-picker1');
            setDatePicker('date-picker2');
            setupDialogBox('dialog', 'opener');
            $('input[type="checkbox"]').fancybutton();
            $('input[type="radio"]').fancybutton();

            $('.datatable').dataTable();
            setSidebarHeight();
            $("#example_info").text("1 到 10 条");
            $("#example_filter label").html("<label>搜索: <input type='text'></label>");
            $("#example_length").html('<label>显示 <select size="1" name="example_length"><option value="10" selected="selected">10</option><option value="25">25</option><option value="50">50</option><option value="100">100</option></select> 条</label>');
            $(".grid_10").css("width", "100%");
            $("#example_filter").remove();
        });
    </script>
    <style>
        body {
            font-size:15px;
        }
        .prev-next {
            position: absolute;
            bottom: 15px;
            right: 100px;
        }

            .prev-next a {
                font-weight: bolder;
                text-decoration: underline
            }
    </style>
</head>
<body>
    <div class="container_12">
        <div class="grid_12 header-repeat">
            <div id="branding">
                <div class="floatleft" style="color: white;font-size: 25px;">
                    中长途旅客出行线路规划平台
                    @*<img src="~/img/logo.png" alt="Logo" />*@
                </div>
                <div class="clear">
                </div>
            </div>
        </div>
        <div class="clear">
        </div>
        <div class="grid_12">
            <ul class="nav main">
                <li class="ic-dashboard"><a href="dashboard.html"><span>数据集展示</span></a></li>
                <li class="ic-form-style"><a href="/Line/Search?type=1"><span>线路查询</span></a></li>
                @*<li class="ic-grid-tables"><a href="/Line/Search?type=2"><span>算法比较</span></a></li>*@
            </ul>
        </div>
        <div class="clear">
        </div>
        <div class="grid_10">
            <div class="box round first grid">
                <h2>
                    @ViewData["Title"]
                </h2>
                <div class="block">
                    @RenderBody()
                </div>
            </div>
        </div>
        <div class="clear">
        </div>
    </div>
    <div class="clear">
    </div>
    <div id="site_info">
        <!-- <p>
            Copyright <a href="#">BlueWhale Admin</a>. All Rights Reserved.More Templates <a href="http://www.cssmoban.com/" target="_blank" title="模板之家">模板之家</a> - Collect from <a href="http://www.cssmoban.com/" title="网页模板" target="_blank">网页模板</a>
        </p> -->
    </div>
    <div class="prev-next">
        <a>上一页</a>
        <a>下一页</a>
    </div>
</body>
</html>